// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlL5ieWo7KdI5wPU0Y6RfgpLevAFTXQFo',
    appId: '1:814959952725:web:3dc12b5415fc11fd1e25dc',
    messagingSenderId: '814959952725',
    projectId: 'sinclear-beyond',
    authDomain: 'sinclear-beyond.firebaseapp.com',
    storageBucket: 'sinclear-beyond.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4Hl9zij69G66yoDNdZN9wqW27BdMYDl4',
    appId: '1:814959952725:android:7ece9d6b23a67a211e25dc',
    messagingSenderId: '814959952725',
    projectId: 'sinclear-beyond',
    storageBucket: 'sinclear-beyond.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlL5ieWo7KdI5wPU0Y6RfgpLevAFTXQFo',
    appId: '1:814959952725:web:901ae56cbe84a75f1e25dc',
    messagingSenderId: '814959952725',
    projectId: 'sinclear-beyond',
    authDomain: 'sinclear-beyond.firebaseapp.com',
    storageBucket: 'sinclear-beyond.firebasestorage.app',
  );
}
